version: '3.1'

services:
  postgres_weather:
    image: postgres:16
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=weather
    ports:
      - "5433:5432"

  weather:
    build: .
    depends_on:
      - postgres_weather
    ports:
      - "8080:8080"
